apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-spb2-backend1-certmanager-bootstrap
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    repoURL: https://github.com/nomad-mrkn/final-argo.git
    targetRevision: HEAD
    path: shared/jit-rbac-app-template
    helm:
      values: |
        app: certmanager
        namespace: cert-manager
        clusterName: kind-test-1
        chartRepo: https://github.com/nomad-mrkn/charts.git
        chartPath: cert-manager
        helmValues: |
          installCRDs: true
          startupapicheck:
            enabled: false
  syncPolicy:
    automated:
      prune: true
