# Required parameters
app: ""
namespace: ""
clusterName: ""
chartRepo: ""
chartPath: ""

# Optional
helmValues: ""
appPrefix: k8s-spb2-backend1
repoURL: https://github.com/nomad-mrkn/final-argo.git
targetRevision: HEAD
